FROM python:3.10-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY src/ ./src/
COPY configs/ ./configs/

EXPOSE 5000
CMD ["python", "src/node_agent/feature_server.py"]